services:
  - type: web
    name: bookclub
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build && blitz prisma migrate deploy --preview-feature
    startCommand: blitz start
    envVars:
      # ⚠️  You must set SESSION_SECRET_KEY env var through the UI.
      # Add this env name, then a "generate" button will appear in the value box
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bookclub-db
          property: connectionString

databases:
  - name: bookclub-db
    plan: starter
